# Generated by Django 5.1.1 on 2024-09-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_data_post_alter_blog_discripton'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='discripton_be',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='discripton_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='discripton_pl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='discripton_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_be',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_pl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
